hmrc/advance-valuation-rulings-frontend

build.sbt
The name change is causing the build to fail and we have no 2_13 releases so I don't think SM will work either 😿 
As this cannot build, I do not believe these changes have been deployed to any environment. Frontend build 41 has these changes applied and builds successfully, so we can at least deploy that whilst we look into updating this
=> Revert Project Name Change

app/config/Module.scala
This change makes Auth (or the auth stub) a requirement to run the service
The configuration has been set at the base level to use the stubbed instance in https://github.com/hmrc/app-config-base/pull/8094
=> ARS-531 Use Auth for session identifiers

app/controllers/CheckRegisteredDetailsController.scala
This shortens the acknowledgementReference to 32 chars as recommended in the ETMP schema doc
=> ARS-555: Shorten ack ref to 32 chars

app/connectors/BackendConnector.scala
This sends the correlation Id header to the backend for tracing requests in Kibana
=> ARS-555: Send correlation Id header to backend

app/config/FrontendAppConfig.scala, app/connectors/BackendConnector.scala, app/controllers/CheckRegisteredDetailsController.scala, app/models/AcknowledgementReference.scala, app/models/EoriNumber.scala, app/viewmodels/checkAnswers/CheckRegisteredDetailsSummary.scala, it/connectors/BackendConnectorSpec.scala, it/utils/BaseIntegrationSpec.scala, it/utils/WireMockHelper.scala, project/AppDependencies.scala, test-utils/generators/Generators.scala, test-utils/generators/TraderDetailsGenerator.scala, test/controllers/CheckRegisteredDetailsControllerSpec.scala
This PR:
- Uses a GET request to retrieve the registered details from the backend
- Fixes the `CheckYourAnswers` page to use the registered details previously retrieved
=> ARS-483: Use GET request for trader details

app/models/UserAnswers.scala
The application number now fits within the header/banner:
=> ARS-430: Use unique ObjectId as the applicationNumber

app/views/CheckRegisteredDetailsView.scala.html, app/views/components/headingH3.scala.html, conf/messages.en
This PR aligns the registered details page with the recent changes on the prototype. The resulting page now looks like below:
=> ARS-706: Align registered details page with prototype

app/views/CheckYourAnswersView.scala.html
The spacing between the sections is now fixed as shown in the image:
=> ARS-731: Fix trader check your answers page misalignment

app/connectors/BackendConnector.scala, app/models/requests/Applicant.scala, app/models/requests/ApplicationRequest.scala, app/viewmodels/checkAnswers/CheckRegisteredDetailsForAgentsSummary.scala, app/viewmodels/checkAnswers/CheckRegisteredDetailsSummary.scala, test-utils/generators/ApplicationRequestGenerator.scala, test/controllers/ViewApplicationControllerSpec.scala, test/models/requests/ApplicantSpec.scala, test/models/requests/ApplicationRequestSpec.scala, test/models/requests/GoodsDetailsSpec.scala, test/models/requests/RequestedMethodSpec.scala
This PR extracts the `eoriDetails` from the applicant(s) into its own field in the application model:
```scala
case class ApplicationRequest(
applicationNumber: String,
eoriDetails: EORIDetails,
applicant: Applicant,
requestedMethod: RequestedMethod,
goodsDetails: GoodsDetails,
attachments: Seq[Attachment]
)
```
=> ARS-740: Make eoriDetails a separate model field

app/views/ApplicationCompleteView.scala.html
This removes the back button from the application complete page.
=> ARS-742: Remove back button fro application complete page

app/models/CheckRegisteredDetails.scala, app/models/TraderDetailsWithCountryCode.scala, app/models/requests/ApplicationRequest.scala, app/viewmodels/checkAnswers/CheckRegisteredDetailsForAgentsSummary.scala, app/viewmodels/checkAnswers/CheckRegisteredDetailsSummary.scala, app/viewmodels/checkAnswers/summary/ApplicantSummary.scala, app/views/CheckRegisteredDetailsView.scala.html, conf/messages.en, it/connectors/BackendConnectorSpec.scala, project/AppDependencies.scala, test-utils/generators/ApplicationRequestGenerator.scala, test-utils/generators/ModelGenerators.scala, test-utils/generators/TraderDetailsGenerator.scala, test/controllers/CheckRegisteredDetailsControllerSpec.scala, test/controllers/CheckYourAnswersControllerSpec.scala, test/controllers/CheckYourAnswersForAgentsControllerSpec.scala, test/controllers/EORIBeUpToDateControllerSpec.scala, test/controllers/ViewApplicationControllerSpec.scala, test/models/CheckRegisteredDetailsSpec.scala, test/models/requests/ApplicationRequestSpec.scala, test/models/requests/ContactDetailsSpec.scala, test/navigation/CheckModeNavigatorSpec.scala, test/navigation/NavigatorSpec.scala, test/services/SubmissionServiceSpec.scala, test/viewmodels/ApplicationViewModelSpec.scala, test/viewmodels/checkAnswers/summary/BusinessEoriDetailsSummarySpec.scala, test/viewmodels/checkAnswers/summary/IndividualEoriDetailsSummarySpec.scala
This hides the trader's personal details when `consentToDisclosureOfPersonalData` is false.
=> ARS-784: Hide trader details when consentToDisclosureOfPersonalData is false

app/connectors/UserAnswersConnector.scala, app/models/requests/ApplicationRequest.scala, app/viewmodels/checkAnswers/CheckRegisteredDetailsSummary.scala, app/viewmodels/checkAnswers/summary/ApplicantSummary.scala, app/views/components/ForYourRecords.scala.html, it/connectors/BackendConnectorSpec.scala, it/connectors/UserAnswersConnectorSpec.scala, project/AppDependencies.scala, test-utils/generators/ApplicationRequestGenerator.scala, test/controllers/ViewApplicationControllerSpec.scala, test/models/requests/ApplicationRequestSpec.scala, test/models/requests/ContactDetailsSpec.scala, test/services/SubmissionServiceSpec.scala, test/viewmodels/ApplicationViewModelSpec.scala
As agreed, the trader private details are now excluded from the application detail page.
=> Exclude trader details from view application page

app/views/RequiredInformationView.scala.html
As recommended by the accessibility audit. This removed the cancel link from the requiredInformation page.
=> ARS-787: Remove cancel link from required info page

app/views/CheckRegisteredDetailsView.scala.html, conf/messages.en
This implements the suggested accessibility recommendation of making the title same as the h1 on the ImportGoods and CheckRegisteredDetails pages
=> ARS-803: Title same as h1 on importGoods and regDetailsPage

app/views/components/Caption.scala.html
This uses h2 captions as recommended by the accessibility audit.
=> ARS-789: Use h2 captions for accessibility

app/views/CommodityCodeView.scala.html
- global error moved to top of main section of page
=> A11y bug: Global error position fixed

app/views/CancelAreYouSureView.scala.html, app/views/templates/Layout.scala.html
This hides the back link when JS is disabled as recommended by the accessibility audit.
=> ARS-809: Hide back link when js is disabled

app/views/CancelAreYouSureView.scala.html
Reverts hmrc/advance-valuation-rulings-frontend#294
Required to revert 824 for a quick deploy
=> Revert "ARS-824 Remove return to application button"

.github/pull_request_template.md
Jira link: [ARSSTB-151 Set up gitHub PR description template](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-151)
The idea of this ticket is to provide a template for PR descriptions. After merging this branch, anytime someone creates a pull request, the PR description will be pre-populated from the new template.
See the official GitHub guide for more information on how it works:
[Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
[Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
_N / A_
=> ARSSTB-151 Added a PR template for GitHub

project/AppDependencies.scala
- [ x] Non-breaking change
https://jira.tools.tax.service.gov.uk/browse/ARS-963
update hmrcMongoVersion to 1.2.0 where timeout is 5 seconds
=> ARS-963: Update MongoVersion to 1.2.0 (Frontend)

app/views/UploadAnotherSupportingDocumentView.scala.html
Just updating the link identifier to ease acceptance testing.  Required change for the following tests:  https://github.com/hmrc/advance-valuation-rulings-acceptance/pull/65
=> ARS-855 Update removal link id

app/controllers/IsThisFileConfidentialController.scala, app/controllers/RemoveSupportingDocumentController.scala, app/controllers/UploadSupportingDocumentsController.scala, app/controllers/callback/UploadCallbackController.scala, app/models/requests/AttachmentRequest.scala, app/navigation/CheckModeNavigator.scala, app/navigation/Navigator.scala, app/pages/IsThisFileConfidentialPage.scala, app/pages/UploadSupportingDocumentPage.scala, app/queries/AllDocuments.scala, app/services/fileupload/FileService.scala, app/views/IsThisFileConfidentialView.scala.html, conf/app.routes, conf/prod.routes, test-utils/generators/PageGenerators.scala, test-utils/generators/UserAnswersEntryGenerators.scala, test-utils/generators/UserAnswersGenerator.scala, test/controllers/IsThisFileConfidentialControllerSpec.scala, test/controllers/RemoveSupportingDocumentControllerSpec.scala, test/controllers/UploadAnotherSupportingDocumentControllerSpec.scala, test/controllers/UploadSupportingDocumentsControllerSpec.scala, test/controllers/callback/UploadCallbackControllerSpec.scala, test/models/requests/AttachmentRequestSpec.scala, test/navigation/CheckModeNavigatorSpec.scala, test/navigation/NavigatorSpec.scala, test/pages/DoYouWantToUploadDocumentsPageSpec.scala, test/pages/IsThisFileConfidentialPageSpec.scala, test/services/fileupload/FileServiceSpec.scala
Essentially, unless a file has completed the file upload journey (uploaded successfully AND has confidentially market) it will not progress to the `AllDocuments` list. This prevents issues with invalid states within AllDocuments, which were easily repeatable by using the back button, loading a draft application, or url hacking
This fixes the underlying issue for ARS-950 and ARS-951
Note the acceptance tests already pass with these changes
The only draft applications that would be affected by these changes would be those with broken file upload journeys. In the current system, such  applications require all files to be removed and then reuploaded to be fixed. The same steps would fix them with this change -- so they are unaffected by this change
Handling an 'initiated' only upload …
=> ARS-950 Handle incomplete file upload journeys

app/models/Country.scala, app/views/AgentCompanyDetailsView.scala.html, app/views/AgentForOrgCheckRegisteredDetailsView.scala.html, app/views/AgentForTraderCheckRegisteredDetailsView.scala.html, app/views/EmployeeCheckRegisteredDetailsView.scala.html
jira: [ARSSTB-206](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-206)
- Odd bug where the SaveAsDraft button was only submitting as saveDraft = false (specified in formhelper)
Removing a cssClass "autocomplete" fixes this - also not a necessary attribute.
- some copyright updated on compile
=> BUG-FIX: Remove breaking css class autocomplete & copyright change

app/controllers/ProvideTraderEoriController.scala, app/controllers/common/TraderDetailsHelper.scala, app/forms/TraderEoriNumberFormProvider.scala, conf/messages.cy, conf/messages.en, test/controllers/ProvideTraderEoriControllerSpec.scala, test/controllers/common/TraderDetailsHelperSpec.scala
fixed issue where supplied eori wasn't sent to backend
fixed issue where special characters weren't checked for correctly
preserved default error case (though using duplicate messaging)
improved default and special character case messaging
=> various provide-trader-eori fixes

app/controllers/VerifyTraderEoriController.scala, app/models/TraderDetailsWithConfirmation.scala, test/controllers/VerifyTraderEoriControllerSpec.scala
Jira link: [Registration details should save the state of selected radio button when Save and continue button is clicked](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-296)
If a user has answered, saved and returned to the check-trader-details screen, this will pre-populate the screen with the given answer.
=> Arsstb 296

app/views/VerifyPublicTraderDetailView.scala.html, conf/messages.cy, conf/messages.en
Message parameter was missing on this page where it should pull through the eori number of the details
=> [FIX] - eori parameter missing from heading - put in

app/controllers/EORIBeUpToDateController.scala
Jira link: [Regression bug: Journey for 'Employee' and 'Agent of Org' journey is broken](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-353)
Assume that the user does not consent to disclose personal data unless they select the agent for trader role. In this case, check their consent. The journey recovery page has been removed since the page should be displayed in all cases.
Employee role:
Agent for organisation role:
Agent for trader role:
=> Fix failing UI tests

app/views/UploadLetterOfAuthorityView.scala.html
Jira link: [Add Save as draft button to Upload Letter of Authority Page](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-326)
Add save as draft button for upload letter of authority view.
=> feat: add save as draft button for upload letter of authority view

app/views/components/ForYourRecords.scala.html
'what happens next' moved up and now inline (removed superfluous div)
=> ARSSTB-360: small tweak

app/views/ExplainWhyYouChoseMethodFourView.scala.html
Jira link: [Unhelpful hint text](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-230)
Revert a previous change which added a bold subheading label for the explain why method 4 page.
=> 230: Remove bold subheading label from the explain why method 4 page

app/controllers/IsThisFileConfidentialController.scala, app/controllers/UploadInProgressController.scala, app/controllers/UploadSupportingDocumentsController.scala, app/controllers/common/FileUploadHelper.scala, app/views/UploadInProgressView.scala.html, conf/app.routes, test/controllers/UploadInProgressControllerSpec.scala, test/controllers/UploadSupportingDocumentsControllerSpec.scala
Jira link: [Browser back from Upload In Progress page causes error](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-394)
The fix is to check if the a file has the "Success" status in the UploadInProgressController and UploadSupportingDocumentsController controllers and in this case remove the file and redirect to the fallback page (UploadSupportingDocumentPage).
Note that under normal operation, the UploadSupportingDocumentsController.onPageLoad and UploadInProgressController.onPageLoad methods will not have the "Success" status.
=> Arsstb 394 upload atomicity

app/controllers/VerifyTraderEoriController.scala, app/views/ProvideTraderEoriView.scala.html, test/controllers/VerifyTraderEoriControllerSpec.scala
Jira link: [EORI number and option selected on EORI details pages not saved](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-450)
The EORI on the /provide-trader-eori page and the radio button selection on the /check-trader-EORI-details pages is now saved when the user navigates back through the journey e.g. after saving as draft. Note that the EORI (text field input) is saved when the Save as draft button is selected on the same page whereas the radio button selection is saved when the Save as draft button is selected on a subsequent page. This behaviour is consistent with the rest of the journey.
=> Save EORI and radio button status on 2 pages

app/config/FrontendAppConfig.scala, conf/application.conf, test/controllers/CheckYourAnswersControllerSpec.scala, test/controllers/CheckYourAnswersForAgentsControllerSpec.scala, test/controllers/UploadSupportingDocumentsControllerSpec.scala
Jira link: [Set Agent Creds feature flag default to true](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-431)
This simple change turns the agent creds feature on permanently, regardless of the application configuration.
Note: removing the parts that check for the flag is not in scope for this ticket (that will come after we successfully released the application into production.
Note #2: The UI tests must be adjusted after this PR is merged, because there's no way to turn agent creds off any more.
=> ARSSTB-431 Turning agent creds on permanently

app/views/UploadLetterOfAuthorityView.scala.html, app/views/UploadSupportingDocumentsView.scala.html, test/controllers/FileUploadHelperSpec.scala, test/controllers/UploadInProgressControllerSpec.scala
Jira link: [Use FormWithCSRF in UploadSupportingDocumentsView](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-417)
Added CSRF token using helpers to both UploadSupportingDocumentsView and UploadLetterOfAuthorityView.
=> added CSRF tokens to supported documents and letter of authority page

app/views/AreThereRestrictionsOnTheGoodsView.scala.html, app/views/DoYouWantToUploadDocumentsView.scala.html, app/views/HasCommodityCodeView.scala.html, app/views/HasConfidentialInformationView.scala.html, app/views/HaveTheGoodsBeenSubjectToLegalChallengesView.scala.html, app/views/HaveYouUsedMethodOneForSimilarGoodsInPastView.scala.html, app/views/HaveYouUsedMethodOneInPastView.scala.html, app/views/IsSaleBetweenRelatedPartiesView.scala.html, app/views/IsTheSaleSubjectToConditionsView.scala.html, app/views/IsThisFileConfidentialView.scala.html, app/views/UploadAnotherSupportingDocumentView.scala.html, app/views/WhatIsYourRoleAsImporterView.scala.html, app/views/components/DescribeRoleRadios.scala.html, app/views/components/LegendH2.scala.html, app/views/components/YesNoRadios.scala.html
Legends have been added to all radio input fieldsets, and I can't find other cases where this is an issue. I'm confident there's no solution much cleaner than this. 
For a good few hours I looked at and experimented with the hmrc components and there isn't a way to allow content between the legend and the actual radio inputs. Our use case is unique in this way. This is loosely confirmed by Adam's comment "The fix is not trivial.".
I've implemented reusable components for radios where the legend is present and form errors are correctly displayed.
=> ARSSTB-500 Legends added to Fieldsets

app/views/AccountHomeView.scala.html
Jira link: ["Your applications" list actions don't include contextual information [WCAG A]](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-492)
Add hidden contextual information to the actions links on the Your applications page. This has been checked for "Continue application", "Delete application" and "View application" actions.
The hidden text has the form: \<Action\> \<Reference\>
See the attached screenshot to see the HTML elements.
EDIT: The hyphen has been removed (not reflected in the screenshot)
=> ARSSTB-492

app/views/templates/Layout.scala.html, project/AppDependencies.scala
Updated PlayFrontendHmrc to major version 7 
Only thing I had to change was that nonce is no longer a parameter in hmrcLayout
I think it gets it from the request now. That's what the changelog seems to imply 
https://github.com/hmrc/play-frontend-hmrc/blob/4a55049a878ada8c47ac378cae79a0006eb16a11/CHANGELOG.md?plain=1#L297
=> Upgraded PlayFrontendHmrcVersion to 7.23.0-play-28

app/viewmodels/govuk/CharacterCountFluency.scala, app/viewmodels/govuk/LabelFluency.scala, app/viewmodels/govuk/package.scala, app/views/ApplicationCompleteView.scala.html, app/views/ConfidentialInformationView.scala.html, app/views/DescribeTheConditionsView.scala.html, app/views/DescribeTheIdenticalGoodsView.scala.html, app/views/DescribeTheLegalChallengesView.scala.html, app/views/DescribeTheRestrictionsView.scala.html, app/views/DescribeTheSimilarGoodsView.scala.html, app/views/ExplainHowPartiesAreRelatedView.scala.html, app/views/ExplainHowYouWillUseMethodSixView.scala.html, app/views/ExplainReasonComputedValueView.scala.html, app/views/ExplainWhyYouChoseMethodFourView.scala.html, app/views/ExplainWhyYouHaveNotSelectedMethodOneToFiveView.scala.html, app/views/ExplainWhyYouHaveNotSelectedMethodOneToThreeView.scala.html, app/views/TellUsAboutYourRulingView.scala.html, app/views/WhyComputedValueView.scala.html, app/views/WhyIdenticalGoodsView.scala.html, app/views/WhyTransactionValueOfSimilarGoodsView.scala.html, conf/messages.cy, conf/messages.en
[Jira link](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-427)
Replace textareas with character count components, which provides feedback on the number of characters the user has remaining, or how many they are over the limit.
Because users are unlikely to come close to the limit, a threshold of 75% has been added (meaning the character count doesn't display until the user has entered 75% of the allowed character count).  This is advised by the GOV.UK design system.
=> ARSSTB-427: Replace textareas with character count component

app/controllers/common/FileUploadHelper.scala, conf/application.conf, test/controllers/FileUploadHelperSpec.scala
Jira link: [No files selected error handling is not accessible [WCAG A]](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-564)
Introduce a minimum file size so that upscan can catch this error when no file has been chosen by the user to upload.
Note that this is not testable locally since the issue is not visible in the local environment (due to the fact that we are interacting with upscan-stub locally).
=> ARSSTB-564

app/viewmodels/checkAnswers/AgentForTraderCheckRegisteredDetailsSummary.scala, test/viewmodels/checkAnswers/summary/TraderSummarySpec.scala
Jira link: [Bug - Check your answers page doesn't display letter of authority for private EORI](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-601)
Display letter of authority on check your answers page when the user has not consented to disclosure of personal data.
=> ARSSTB-601

app/views/components/SaveButtons.scala.html, app/views/components/SaveButtonsWithTarget.scala.html
Jira link: ["Save as draft" uses "role - button" but is missing data-module from the library](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-495)
Some buttons for "Save and continue" and "Save as draft" were links styled to look like buttons.
To act as buttons they need to have js event handlers applied (so users can use the spacebar to action them, just like real buttons). The best way to do this is to use the lib button component which both applies the styles to the links but also all the aria role and event handlers.
(You can pass an `href` into a Button component and it will generate a link rather than a button element)
=> ARSSTB-495 Update button links to use lib components

app/controllers/UploadAnotherSupportingDocumentController.scala, test/controllers/UploadAnotherSupportingDocumentControllerSpec.scala
Jira link: [Bug - Letter of authority disappears on uploaded supporting docs page](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-598)
Ensure that the letter of authority is shown in the view when the user selects Save and continue without selecting a radio button.
=> Arsstb 598

app/views/UploadAnotherSupportingDocumentView.scala.html
Jira link: [Accessibility Jenkins job failure](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-681)
Fixes markup for showing supporting docs and letter of authority.
Corrected definition list markup for supporting docs.
Updated letter of auth to remove list markup (as only ever going to be one).
=> ARSSTB-681 Updated list markup for docs

app/controllers/AboutSimilarGoodsController.scala, app/controllers/AgentCompanyDetailsController.scala, app/controllers/ApplicationContactDetailsController.scala, app/controllers/BusinessContactDetailsController.scala, app/controllers/CommodityCodeController.scala, app/controllers/ConfidentialInformationController.scala, app/controllers/DescribeTheConditionsController.scala, app/controllers/DescribeTheIdenticalGoodsController.scala, app/controllers/DescribeTheLegalChallengesController.scala, app/controllers/DescribeTheRestrictionsController.scala, app/controllers/DescribeTheSimilarGoodsController.scala, app/controllers/DescriptionOfGoodsController.scala, app/controllers/ExplainHowPartiesAreRelatedController.scala, app/controllers/ExplainHowYouWillUseMethodSixController.scala, app/controllers/ExplainReasonComputedValueController.scala, app/controllers/ExplainWhyYouChoseMethodFourController.scala, app/controllers/ExplainWhyYouHaveNotSelectedMethodOneToFiveController.scala, app/controllers/ExplainWhyYouHaveNotSelectedMethodOneToThreeController.scala, app/controllers/ProvideTraderEoriController.scala, app/controllers/WhyComputedValueController.scala, app/controllers/WhyIdenticalGoodsController.scala, app/controllers/WhyTransactionValueOfSimilarGoodsController.scala, app/views/AboutSimilarGoodsView.scala.html, conf/app.routes, test/controllers/AboutSimilarGoodsControllerSpec.scala
Desired behaviour implemented:
On text fields ----
If a user inputs invalid or no data and clicks save as draft - Discard their input (if any) and save as draft.
If a user inputs valid data and clicks save as draft - Keep their data and save as draft.
If a user just clicks save and continue - continue the journey with saved data.
=> ARSSTB-589 Save as draft on text fields fix

conf/application.conf, test/resources/application.conf
Reverts hmrc/advance-valuation-rulings-frontend#551
Turns out that something to do with this change breaks the back-links functionality.
=> Revert "ARSSTB-539"

app/views/templates/Layout.scala.html, conf/application.conf, test/resources/application.conf
Jira link: [play.filters.headers.contentSecurityPolicy should be removed from config as it is deprecated](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-539)
play.filters.headers.contentSecurityPolicy should be removed from config as it is deprecated
Added CSPNonce to script tags and adapted security directives to allow JS to run
=> ARSSTB-539 added CSPNonce's and directives to repair back buttons
