- .gitignore
- README.md
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
This just fixes the various suggestions by the pr-bot. As seen here: https://github.com/hmrc/advance-valuation-rulings-frontend/pull/2#issuecomment-1361551621
> Various suggestions raised by the PR bot

- app/controllers/AccountHomeController.scala
- app/controllers/CheckRegisteredDetailsController.scala
- app/controllers/RequiredInformationController.scala
- app/forms/CheckRegisteredDetailsFormProvider.scala
- app/models/CheckRegisteredDetails.scala
- app/navigation/Navigator.scala
- app/pages/CheckRegisteredDetailsPage.scala
- app/viewmodels/checkAnswers/CheckRegisteredDetailsSummary.scala
- app/viewmodels/checkAnswers/RequiredInformationSummary.scala
- app/views/AccountHomeView.scala.html
- app/views/CheckRegisteredDetailsView.scala.html
- app/views/ContactPageView.scala.html
- conf/app.routes
- conf/messages.en
- test-utils/generators/PageGenerators.scala
- test-utils/generators/UserAnswersEntryGenerators.scala
- test-utils/generators/UserAnswersGenerator.scala
- test/controllers/AccountHomeControllerSpec.scala
- test/controllers/CheckRegisteredDetailsControllerSpec.scala
- test/controllers/RequiredInformationControllerSpec.scala
- test/forms/CheckRegisteredDetailsFormProviderSpec.scala
- test/models/CheckRegisteredDetailsSpec.scala
- test/pages/CheckRegisteredDetailsPageSpec.scala
> ARS-358 Start page and reg address check page

- app/config/FrontendAppConfig.scala
- app/viewmodels/govuk/RadiosFluency.scala
- app/views/HasCommodityCodeView.scala.html
- conf/application.conf
- conf/messages.en
> ARS-403 Has commodity code page

- app/forms/CommodityCodeFormProvider.scala
- app/forms/mappings/Constraints.scala
- app/views/CommodityCodeView.scala.html
- app/views/components/CancelApplicationLink.scala.html
- conf/app.routes
- conf/messages.en
- test-utils/generators/Generators.scala
- test/controllers/CommodityCodeControllerSpec.scala
- test/forms/CommodityCodeFormProviderSpec.scala
- test/forms/behaviours/StringFieldBehaviours.scala
https://user-images.githubusercontent.com/8013000/211034066-07497698-6201-425a-bab2-666b47ee5c9d.mov
> ARS-404 :Commodity code page updated with validation and content

- app/viewmodels/govuk/ButtonFluency.scala
We'll be using this quite often, so useful to introduce a helper extension method
> Add withAttribute extension method to Button helpers

- app/views/CheckRegisteredDetailsView.scala.html
- app/views/components/Warning.scala.html
- conf/messages.en
Does **not** include navigation, as the pages do not exist
> ARS-433 Check registered details page

- app/navigation/Navigator.scala
- test/controllers/HasCommodityCodeControllerSpec.scala
- test/controllers/MustHaveCommodityCodeControllerSpec.scala
Navigate to the new page when selecting "No" instead of the index page
> ARS-364 Navigate from has commodity code page to must have code page

- app/config/FrontendAppConfig.scala
- app/controllers/EORIBeUpToDateController.scala
- app/navigation/Navigator.scala
- app/views/EORIBeUpToDateView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- test/controllers/EORIBeUpToDateControllerSpec.scala
> ARS-434: Created EORI Must be up to date page

- app/views/HasCommodityCodeView.scala.html
https://user-images.githubusercontent.com/8013000/212334020-7733a8d4-a304-429a-85b4-e1f6f9a0704c.mov
> ARS-480 Open search for commodity code link in new tab

- app/controllers/HasConfidentialInformationController.scala
- app/models/UserAnswers.scala
- app/views/HasConfidentialInformationView.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/HasConfidentialInformationControllerSpec.scala
https://user-images.githubusercontent.com/8013000/212344387-eedbd22d-5b14-4b4d-8beb-bd08296367ff.mov
> ARS-436 Do you want to add confidential information page

- app/controllers/ConfidentialInformationController.scala
- app/controllers/DoYouWantToUploadDocumentsController.scala
- app/controllers/HasConfidentialInformationController.scala
- app/controllers/IsThisFileConfidentialController.scala
- app/controllers/UploadAnotherSupportingDocumentController.scala
- app/controllers/UploadSupportingDocumentsController.scala
- app/forms/DoYouWantToUploadDocumentsFormProvider.scala
- app/forms/IsThisFileConfidentialFormProvider.scala
- app/forms/UploadAnotherSupportingDocumentFormProvider.scala
- app/navigation/Navigator.scala
- app/viewmodels/checkAnswers/DoYouWantToUploadDocumentsSummary.scala
- app/viewmodels/checkAnswers/IsThisFileConfidentialSummary.scala
- app/viewmodels/checkAnswers/UploadAnotherSupportingDocumentSummary.scala
- app/viewmodels/govuk/TextareaFluency.scala
- app/views/ConfidentialInformationView.scala.html
- app/views/components/InsetPara.scala.html
- conf/messages.en
- test-utils/generators/PageGenerators.scala
- test-utils/generators/UserAnswersEntryGenerators.scala
- test-utils/generators/UserAnswersGenerator.scala
- test/controllers/ConfidentialInformationControllerSpec.scala
- test/controllers/DoYouWantToUploadDocumentsControllerSpec.scala
- test/controllers/IsThisFileConfidentialControllerSpec.scala
- test/controllers/UploadAnotherSupportingDocumentControllerSpec.scala
- test/controllers/UploadSupportingDocumentsControllerSpec.scala
- test/forms/DoYouWantToUploadDocumentsFormProviderSpec.scala
- test/forms/IsThisFileConfidentialFormProviderSpec.scala
- test/forms/UploadAnotherSupportingDocumentFormProviderSpec.scala
- test/pages/ApplicationContactDetailsPageSpec.scala
This contains some of the components used in #25 They should just be a straight copy/paste across, so it shouldn't matter which is merged first
https://user-images.githubusercontent.com/8013000/212887725-55c622ad-a854-44f2-8637-c61b8dd6a6d9.mov
> ARS-437 What confidential information would you like to add?

- app/forms/DescribeTheGoodsFormProvider.scala
- app/forms/HowAreTheGoodsMadeFormProvider.scala
- app/viewmodels/govuk/TextareaFluency.scala
- app/views/DescribeTheGoodsView.scala.html
- app/views/HowAreTheGoodsMadeView.scala.html
- conf/messages.en
- test/forms/DescribeTheGoodsFormProviderSpec.scala
- test/forms/HowAreTheGoodsMadeFormProviderSpec.scala
text area rows increased, has a max allowable length but also an length error message
> ARS-365: Post-Review changes

- app/config/FrontendAppConfig.scala
- conf/application.conf
- conf/prod.routes
changed to **advance-valuation-ruling**
> ARS-489: change of user facing url

- README.md
- build.sbt
- conf/application.conf
Updated with port number used in pipeline
> Update port number

- conf/messages.en
> ARS-455 Updated error message

- app/navigation/Navigator.scala
- app/views/AreThereRestrictionsOnTheGoodsView.scala.html
- app/views/DescribeTheConditionsView.scala.html
- app/views/DescribeTheRestrictionsView.scala.html
- app/views/IsTheSaleSubjectToConditionsView.scala.html
- test/navigation/NavigatorSpec.scala
https://user-images.githubusercontent.com/8013000/220080289-a85df82e-dc6b-4274-8040-caee4f63d7d3.mov
> ARS-543 Method 1 Question Set 2 Navigation and Views

- app/connectors/UpscanInitiateConnector.scala
- app/controllers/IsThisFileConfidentialController.scala
- app/repositories/FileUploadRepository.scala
- app/repositories/SessionRepository.scala
- build.sbt
- it/repositories/SessionRepositorySpec.scala
- project/AppDependencies.scala
- test-utils/generators/Generators.scala
- test/forms/DescribeTheLegalChallengesFormProviderSpec.scala
- test/forms/HaveTheGoodsBeenSubjectToLegalChallengesFormProviderSpec.scala
- test/navigation/NavigatorSpec.scala
And some tougher compiler settings 😈
> Bootstrap Test dependency / compiler settings

- app/navigation/Navigator.scala
- conf/messages.en
- test/navigation/NavigatorSpec.scala
> ARS-609: content + nav fix

- app/controllers/IsThisFileConfidentialController.scala
- app/controllers/UploadAnotherSupportingDocumentController.scala
- app/controllers/fileupload/UploadSupportingDocumentsController.scala
- app/models/SupportingDocumentsTable.scala
- app/navigation/CheckModeNavigator.scala
- app/navigation/Navigator.scala
- app/services/fileupload/FileUploadService.scala
- conf/app.routes
- test/controllers/ImportGoodsControllerSpec.scala
- test/controllers/UploadAnotherSupportingDocumentControllerSpec.scala
- test/controllers/UploadSupportingDocumentsControllerSpec.scala
- test/navigation/CheckModeNavigatorSpec.scala
- test/navigation/NavigatorSpec.scala
- test/services/FakeFileUploadService.scala
https://user-images.githubusercontent.com/8013000/223720605-14eb9d7f-05d6-4279-a0f1-c587069c52a0.mov
> ARS-520 Check your answers navigation (post method questions)

- app/forms/ApplicationContactDetailsFormProvider.scala
- conf/messages.en
- test-utils/generators/Generators.scala
- test/controllers/ApplicationCompleteControllerSpec.scala
- test/controllers/ApplicationContactDetailsControllerSpec.scala
- test/forms/ApplicationContactDetailsFormProviderSpec.scala
- test/forms/behaviours/StringFieldBehaviours.scala
[ARS-661](https://jira.tools.tax.service.gov.uk/browse/ARS-661)
> ARS-661: contact details validation

- app/controllers/ApplicationCompleteController.scala
- app/viewmodels/checkAnswers/summary/ApplicantSummary.scala
- app/viewmodels/checkAnswers/summary/ApplicationSummary.scala
- app/viewmodels/checkAnswers/summary/DetailsSummary.scala
- app/viewmodels/checkAnswers/summary/MethodSummary.scala
- app/views/ApplicationCompleteView.scala.html
- test/controllers/ApplicationCompleteControllerSpec.scala
https://user-images.githubusercontent.com/8013000/225014271-9cc25e54-6b68-425a-8ecb-d8c3fbc7b3df.mov
> ARS-587 Simple application view

- app/controllers/WhatIsYourRoleAsImporterController.scala
- app/controllers/WhoAreYouAgentController.scala
- app/forms/WhatIsYourRoleAsImporterFormProvider.scala
- app/forms/WhoAreYouAgentFormProvider.scala
- app/models/WhatIsYourRoleAsImporter.scala
- app/pages/WhatIsYourRoleAsImporterPage.scala
- app/pages/WhoAreYouAgentPage.scala
- app/viewmodels/checkAnswers/WhatIsYourRoleAsImporterSummary.scala
- app/viewmodels/checkAnswers/WhoAreYouAgentSummary.scala
- app/views/WhatIsYourRoleAsImporterView.scala.html
- app/views/WhoAreYouAgentView.scala.html
- conf/app.routes
- conf/messages.en
- test-utils/generators/ModelGenerators.scala
- test-utils/generators/PageGenerators.scala
- test-utils/generators/UserAnswersEntryGenerators.scala
- test/controllers/WhatIsYourRoleAsImporterControllerSpec.scala
- test/controllers/WhoAreYouAgentControllerSpec.scala
- test/forms/WhatIsYourRoleAsImporterFormProviderSpec.scala
- test/forms/WhoAreYouAgentFormProviderSpec.scala
- test/models/WhatIsYourRoleAsImporterSpec.scala
- test/pages/WhatIsYourRoleAsImporterPageSpec.scala
- test/pages/WhoAreYouAgentPageSpec.scala
scaffold for [ARS-644](https://jira.tools.tax.service.gov.uk/browse/ARS-644) and [ARS-645](https://jira.tools.tax.service.gov.uk/browse/ARS-645)
> Scaffold agents

- app/connectors/BackendConnector.scala
- app/models/requests/ApplicationRequest.scala
- test-utils/generators/ApplicationRequestGenerator.scala
- test/controllers/ViewApplicationControllerSpec.scala
- test/models/requests/ApplicationRequestSpec.scala
This adds the application number to the new model
> Add application number to new model

- app/controllers/AccountHomeController.scala
- app/controllers/RequiredInformationController.scala
- app/controllers/WhatIsYourRoleAsImporterController.scala
- app/controllers/actions/ApplicationNumberGenerationAction.scala
- app/models/WhatIsYourRoleAsImporter.scala
- app/models/requests/ApplicationNumberRequest.scala
- app/navigation/Navigator.scala
- app/views/WhatIsYourRoleAsImporterView.scala.html
- conf/app.routes
- conf/messages.en
- test/navigation/NavigatorSpec.scala
-content on page
-navigation; tested
-Refactor: moved useranswers creation to startApplication on AccountHomeController
> ARS-644:content for role page plus refactor

- app/navigation/Navigator.scala
- conf/app.routes
This attempts to fix the issue in QA where the individual check-your-answers page is shown for an agent.
This only happens in QA and has not been reproducible locally.
> ARS-646: Fix check-you-answers navigation

- app/controllers/CheckRegisteredDetailsController.scala
- app/navigation/Navigator.scala
- test/navigation/FakeNavigator.scala
- test/navigation/NavigatorSpec.scala
This fixes the bug where a successful check on the registered details does not navigate directly to the check-your-answers page.
> ARS-755: Fix registered details navigation in CheckMode

- app/config/FrontendAppConfig.scala
- app/connectors/UpscanInitiateConnector.scala
- app/controllers/UploadAnotherSupportingDocumentController.scala
- app/views/UploadSupportingDocumentsView.scala.html
- conf/application.conf
- conf/messages.en
- test/connectors/UpscanInitiateConnectorSpec.scala
- test/controllers/UploadAnotherSupportingDocumentControllerSpec.scala
The configs are also used to update the messages as shown in the screenshot below:
> ARS-735: Limit uploads to max 5 files of 5Mib each

- app/controllers/HaveYouUsedMethodOneForSimilarGoodsInPastController.scala
- app/controllers/HaveYouUsedMethodOneInPastController.scala
- app/controllers/package.scala
- app/models/UserAnswers.scala
- app/navigation/CheckModeNavigator.scala
- app/views/HaveYouUsedMethodOneForSimilarGoodsInPastView.scala.html
- app/views/HaveYouUsedMethodOneInPastView.scala.html
- conf/messages.en
- test-utils/generators/ApplicationRequestGenerator.scala
- test/models/UserAnswersSpec.scala
- test/models/requests/ApplicantSpec.scala
Method 2:
https://user-images.githubusercontent.com/8013000/229074848-6049caa5-62d9-4f2b-b2a9-99590a817f0d.mov
Method 3:
https://user-images.githubusercontent.com/8013000/229074916-845b82cf-f0fe-45eb-96f0-847022cd4ac5.mov
> ARS-748 Content changes

- app/views/UploadSupportingDocumentsView.scala.html
This is causing Medium ZAP alerts
> ARS-733 Add missing CSRF token to upload form

- app/models/SupportingDocumentsTable.scala
- app/viewmodels/govuk/TableFluency.scala
- app/views/UploadAnotherSupportingDocumentView.scala.html
The formatted uploaded documents table now looks like the screenshot below:
> ARS-763: Fix content display in supporting documents table

- app/controllers/UploadAnotherSupportingDocumentController.scala
- app/controllers/UploadSupportingDocumentsController.scala
- app/models/SupportingDocumentsTable.scala
- app/models/fileupload/UploadStatus.scala
- app/views/UploadSupportingDocumentsView.scala.html
- conf/messages.en
- test/models/fileupload/UploadStatusSpec.scala
This PR:
- Prevents duplicate files from being included in the valuation application
- Prevents removal of uploaded files from opening a new tab
> ARS-766: Prevent duplicate file upload

- app/models/TraderDetailsWithCountryCode.scala
- test-utils/generators/Generators.scala
- test-utils/generators/TraderDetailsGenerator.scala
- test/controllers/CheckRegisteredDetailsControllerSpec.scala
requires https://github.com/hmrc/advance-valuation-rulings/pull/71
> ARS-760 Read contact information in trader details response

- app/audit/AuditService.scala
- app/controllers/AccountHomeController.scala
- app/controllers/WhatIsYourRoleAsImporterController.scala
- app/controllers/actions/DataRequiredAction.scala
- app/controllers/actions/DataRetrievalAction.scala
- app/controllers/actions/IdentifierAction.scala
- app/controllers/actions/IdentifyAgent.scala
- app/controllers/actions/IdentifyIndividual.scala
- app/models/events/AgentIndicatorEvent.scala
- app/models/events/UserTypeEvent.scala
- app/models/requests/DataRequest.scala
- test/audit/AuditServiceSpec.scala
- test/base/SpecBase.scala
- test/controllers/AccountHomeControllerSpec.scala
- test/controllers/WhatIsYourRoleAsImporterControllerSpec.scala
- test/controllers/actions/DataRetrievalActionSpec.scala
- test/controllers/actions/FakeDataRetrievalAction.scala
- test/controllers/actions/FakeIdentifierAction.scala
- test/controllers/actions/FakeIdentifyAgentAction.scala
- test/controllers/actions/FakeIdentifyIndividualAction.scala
- test/controllers/actions/FakeIdentifyOrgAction.scala
- test/controllers/actions/FakeOrgIdentifierAction.scala
This adds the `UserEntersService` and `IndicatesIsAgentEvent` audit events.
> ARS-513: Add audit events

- app/controllers/CheckRegisteredDetailsController.scala
- app/forms/CheckRegisteredDetailsFormProvider.scala
- conf/messages.en
- test/controllers/CheckRegisteredDetailsControllerSpec.scala
- test/forms/CheckRegisteredDetailsFormProviderSpec.scala
> Update error message on check registered details page

- app/controllers/ApplicationCompleteController.scala
- app/viewmodels/checkAnswers/CheckRegisteredDetailsForAgentsSummary.scala
- app/viewmodels/checkAnswers/summary/ApplicantSummary.scala
- app/viewmodels/checkAnswers/summary/ApplicationCompleteSummary.scala
- app/viewmodels/checkAnswers/summary/EoriDetailsSummary.scala
- app/views/ApplicationCompleteView.scala.html
- test/base/SpecBase.scala
- test/controllers/ApplicationCompleteControllerSpec.scala
- test/controllers/actions/FakeAgentIdentifierAction.scala
This uses the application retrieved from the backend in the applicationComplete view page.
> Use submitted application instead of userAnswers

- conf/messages.en
> Service name title updated

- app/views/ViewApplicationView.scala.html
> remove print link

- app/views/ViewApplicationView.scala.html
- app/views/components/PrintApplicationLink.scala.html
> Return of the print link

- app/controllers/CheckYourAnswersForAgentsController.scala
- app/controllers/WhatIsYourRoleAsImporterController.scala
- app/navigation/CheckModeNavigator.scala
- app/viewmodels/checkAnswers/AgentCompanySummary.scala
- app/viewmodels/checkAnswers/BusinessContactDetailsSummary.scala
- app/views/CheckYourAnswersForAgentsView.scala.html
- conf/messages.en
- test/controllers/AgentCompanyDetailsControllerSpec.scala
- test/controllers/CheckYourAnswersForAgentsControllerSpec.scala
- test/controllers/EORIBeUpToDateControllerSpec.scala
- test/controllers/UploadAnotherSupportingDocumentControllerSpec.scala
- test/controllers/WhatIsYourRoleAsImporterControllerSpec.scala
- test/navigation/CheckModeNavigatorSpec.scala
- test/viewmodels/checkAnswers/summary/AgentSummarySpec.scala
> Check answers Agent of Behalf of Org / Org Employee

- app/viewmodels/ApplicationViewModel.scala
- app/viewmodels/checkAnswers/AgentCompanySummary.scala
- app/views/components/ForYourRecords.scala.html
- conf/messages.en
- test/viewmodels/ApplicationViewModelSpec.scala
> View agent details on View Application 

- app/views/CommodityCodeView.scala.html
> commodity code page view fix

- app/controllers/AccountHomeController.scala
- test/controllers/AccountHomeControllerSpec.scala
> ARS-831 Update application order

- app/views/CheckRegisteredDetailsView.scala.html
https://user-images.githubusercontent.com/8013000/234299877-b1503905-8e4c-407e-b60e-f359f40fd4ef.mov
> ARS-823 Update check registered details error summary link

- app/views/templates/Layout.scala.html
> ARS=842 Fix signout link in template

- app/models/ApplicationForAccountHome.scala
- app/views/AccountHomeView.scala.html
- test/controllers/AccountHomeControllerSpec.scala
> ARS-864 Account Home sort order

- app/models/AuthUserType.scala
- test/models/AuthUserTypeSpec.scala
> AuthUserType model

- app/views/ConfidentialInformationView.scala.html
- app/views/DescribeTheConditionsView.scala.html
- app/views/DescribeTheIdenticalGoodsView.scala.html
- app/views/DescribeTheLegalChallengesView.scala.html
- app/views/DescribeTheRestrictionsView.scala.html
- app/views/DescribeTheSimilarGoodsView.scala.html
- app/views/ExplainHowPartiesAreRelatedView.scala.html
- app/views/ExplainHowPartiesAreRelatedViewCOPY.scala.html
- app/views/ExplainHowYouWillUseMethodSixView.scala.html
- app/views/ExplainReasonComputedValueView.scala.html
- app/views/WhyIdenticalGoodsView.scala.html
- app/views/components/Heading.scala.html
> ARS-810: Text area refactor

- app/controllers/CancelApplicationController.scala
- app/forms/CancelApplicationFormProvider.scala
- app/views/CancelAreYouSureView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/CancelApplicationControllerSpec.scala
- test/forms/CancelApplicationFormProviderSpec.scala
https://github.com/hmrc/advance-valuation-rulings-frontend/assets/8013000/93369e11-5dff-498d-937d-15d25540a781
> ARS-824: Confirm cancel application

- app/views/CancelAreYouSureView.scala.html
> ARS-824 Remove return to application button

- app/views/IsThisFileConfidentialView.scala.html
- app/views/UploadSupportingDocumentsView.scala.html
- save as draft buttons removed from upload mini journey
- also covers ARS-951
> ARS-950: save as draft buttons removed from upload mini journey

- conf/app.routes
Jira link: [ARS-852](https://jira.tools.tax.service.gov.uk/browse/ARS-852)
routes checked, dupe add-conf-info routes removed
> ARS-852: routes checked for dupes

- conf/messages.cy
> Welsh update: keep confidential

- app/models/ApplicationForAccountHome.scala
- conf/application.conf
Jira link: [ARS-920](https://jira.tools.tax.service.gov.uk/browse/ARS-920)
> ARS-920: colours added to status tags

- test/forms/ApplicationContactDetailsFormProviderSpec.scala
- test/forms/BusinessContactDetailsFormProviderSpec.scala
[ARS-806](https://jira.tools.tax.service.gov.uk/browse/ARS-806)
> ARS-806 Additional phone number test cases

- app/controllers/DescriptionOfGoodsController.scala
- app/views/DescriptionOfGoodsView.scala.html
- conf/app.routes
- test/controllers/DescriptionOfGoodsControllerSpec.scala
Jira link: https://jira.tools.tax.service.gov.uk/browse/ARSSTB-206
One page missing the draft refactor, picked up during testing - Description of goods page
> ARSSTB-206: description of goods page refactored

- app/userrole/AgentForOrg.scala
- app/userrole/AgentForTrader.scala
- app/userrole/Employee.scala
- app/userrole/UserRole.scala
- app/userrole/UserRoleProvider.scala
- app/views/AgentForOrgCheckRegisteredDetailsView.scala.html
- app/views/AgentForTraderCheckRegisteredDetailsView.scala.html
- app/views/EmployeeCheckRegisteredDetailsView.scala.html
- test/userrole/AgentForOrgSpec.scala
- test/userrole/AgentForTraderSpec.scala
- test/userrole/EmployeeSpec.scala
Not wired in yet, initial model for UserRole logic
> ARSSTB-242: UserRole initial implimentation

- app/userrole/UserRoleProvider.scala
- test/userrole/UserRoleProviderSpec.scala
_Provide a short description of the change. For example: what parts of the code changed, is there any new behaviour...etc._
> Provided implementation for UserRoleProvider

- app/controllers/CheckRegisteredDetailsController.scala
- app/controllers/EORIBeUpToDateController.scala
- app/views/CheckRegisteredDetailsView.scala.html
- app/views/EORIBeUpToDateView.scala.html
- test/controllers/CheckRegisteredDetailsControllerSpec.scala
- test/controllers/EORIBeUpToDateControllerSpec.scala
_Provide a short description of the change. For example: what parts of the code changed, is there any new behaviour...etc._
> add changes allowing flag set and unset

- app/userrole/AgentForOrg.scala
(https://jira.tools.tax.service.gov.uk/browse/ARSSTB-162)
Quick patch to correct routes for AgentsForOrgs
> corrected agentfororg route from contact page

- app/controllers/ProvideTraderEoriController.scala
https://jira.tools.tax.service.gov.uk/browse/ARSSTB-293
Found in testing - we weren't preserving the details in the db as we'd save a modified userAnswers, and then overwrite based on the original userAnswers
> ARSSTB-293 saving trader details off of the provide trader eori save

- app/views/VerifyPublicTraderDetailView.scala.html
- test/controllers/common/TraderDetailsHelperSpec.scala
- test/navigation/NavigatorSpec.scala
> search link fixed

- app/views/InvalidTraderEoriView.scala.html
- app/views/VerifyPrivateTraderDetailView.scala.html
- conf/application.conf
Search again link's fixed (provide trader eori number)
> ARSSTB-165: Search Link Fixes

- app/views/AgentForOrgRequiredInformationView.scala.html
- app/views/AgentForTraderRequiredInformationView.scala.html
- app/views/IndividualInformationRequiredView.scala.html
- conf/messages.en
- [ X ] Cosmetic change
Small changes to content and added cancel buttons, all is working.
Got a little confused at what page it was supposed to be but that's mondays for you, it's fine now, hoping the checks pass.
> ARSSTB-284

- conf/application.conf
Mistakenly switched to true - turning back to false
> [Patch] trader agent feature off

- app/controllers/ProvideTraderEoriController.scala
- app/controllers/VerifyTraderEoriController.scala
- app/models/TraderDetailsWithConfirmation.scala
- app/pages/VerifyTraderDetailsPage.scala
- app/views/ProvideTraderEoriView.scala.html
- app/views/VerifyPrivateTraderDetailView.scala.html
- app/views/VerifyPublicTraderDetailView.scala.html
- conf/app.routes
- test/base/SpecBase.scala
- test/controllers/ProvideTraderEoriControllerSpec.scala
- test/controllers/VerifyTraderEoriControllerSpec.scala
Jira link: [Fix: Provide Trader Eori not populating when reloading page from draft](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-293)
Replaced SaveButtons with SaveButtonsWithDraft and updated urls and controller to react to saveDraft flag.
> fixed draft saving issue

- app/views/AgentForOrgRequiredInformationView.scala.html
- app/views/AgentForTraderRequiredInformationView.scala.html
- app/views/IndividualInformationRequiredView.scala.html
Jira link: https://jira.tools.tax.service.gov.uk/browse/ARSSTB-297
Fixed save buttons on requiredInformation pages (draft will redirect to yourAppHasBeenSaved)
> ARSSTB-297: fix save as draft buttons

- conf/messages.cy
Jira link: [Update the Welsh language file with the new translations](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-304)
There are a couple of new lines translated into Welsh.
> ARSSTB-304 Updated the Welsh language file

- app/connectors/BackendConnector.scala
- it/connectors/BackendConnectorSpec.scala
Jira link: [ARSSTB-165](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-165)
> ARSSTB-165: System Displays Invalid EORI [FRONTEND]

- app/views/AgentForOrgEORIBeUpToDateView.scala.html
- app/views/AgentForTraderEORIBeUpToDateView.scala.html
- app/views/EmployeeEORIBeUpToDateView.scala.html
- app/views/ProvideTraderEoriView.scala.html
- conf/messages.cy
- conf/messages.en
Jira link: [ARSSTB-331](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-331)
> ARSSTB-331: title issues addressed

- app/views/ApplicationCompleteView.scala.html
Jira link: [ARSSTB-228](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-228)
h3's changed to h2's
> ARSSTB-228: Heading structure update

- app/views/AgentForOrgEORIBeUpToDateView.scala.html
- app/views/EmployeeEORIBeUpToDateView.scala.html
Jira link: [ARSSTB-323](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-323)
Corrected message keys for kickout page content
> ARSSTB-323: kickout content

- app/views/InvalidTraderEoriView.scala.html
Title suffix missing on InvalidEORI page - causing failure in UI-Tests
> [CONTENT FIX]: title suffix added to invalid eori page

- app/viewmodels/checkAnswers/ConfidentialInformationSummary.scala
- app/viewmodels/checkAnswers/DescribeTheConditionsSummary.scala
- app/viewmodels/checkAnswers/DescribeTheIdenticalGoodsSummary.scala
- app/viewmodels/checkAnswers/DescribeTheLegalChallengesSummary.scala
- app/viewmodels/checkAnswers/DescribeTheRestrictionsSummary.scala
- app/viewmodels/checkAnswers/DescribeTheSimilarGoodsSummary.scala
- app/viewmodels/checkAnswers/DescriptionOfGoodsSummary.scala
- app/viewmodels/checkAnswers/ExplainHowPartiesAreRelatedSummary.scala
- app/viewmodels/checkAnswers/ExplainHowYouWillUseMethodSixSummary.scala
- app/viewmodels/checkAnswers/ExplainReasonComputedValueSummary.scala
- app/viewmodels/checkAnswers/ExplainWhyYouChoseMethodFourSummary.scala
- app/viewmodels/checkAnswers/ExplainWhyYouHaveNotSelectedMethodOneToFiveSummary.scala
- app/viewmodels/checkAnswers/ExplainWhyYouHaveNotSelectedMethodOneToThreeSummary.scala
- app/viewmodels/checkAnswers/WhyComputedValueSummary.scala
- app/viewmodels/checkAnswers/WhyIdenticalGoodsSummary.scala
- app/viewmodels/checkAnswers/WhyTransactionValueOfSimilarGoodsSummary.scala
Not urgent.
- [ x ] Cosmetic change
Line breaks are now preserved. Checked all journeys.
> Line Break Preservation on CheckYourAnswers

- app/views/VerifyPublicTraderDetailView.scala.html
Should bring accessibility test jenkins job to a stable state.
> Refactored Trader Details View

- app/assets/stylesheets/partials/_view_application.scss
- app/views/ViewApplicationView.scala.html
- app/views/components/AboutTheGoods.scala.html
- app/views/components/ForYourRecords.scala.html
- app/views/templates/Layout.scala.html
Jira link: [ARSSTB-308](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-308)
> ARSSTB-308: Provis fixes to application view/print pages

- app/navigation/Navigator.scala
- app/pages/AgentForOrgCheckRegisteredDetailsPage.scala
- app/userrole/AgentForOrg.scala
Added new page case object, altered agent for org user role to return it, added a part to the navigator to navigate to the correct part of the journey (the right contact details page).
> ARSSTB-348 Wrong contact details page for AgentForOrg

- app/assets/stylesheets/partials/_view_application.scss
- app/views/ViewApplicationView.scala.html
- conf/messages.en
[ARSSTB-231](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-231)
- changes already added from [ARSSTB-308](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-308)
- format changes made
> ARSSTB-231: Print preview page

- app/controllers/UploadLetterOfAuthorityController.scala
- app/controllers/UploadSupportingDocumentsController.scala
- conf/messages.cy
- conf/messages.en
- test/controllers/UploadLetterOfAuthorityControllerSpec.scala
- test/controllers/UploadSupportingDocumentsControllerSpec.scala
Jira link: [ARSSTB-170](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-170)
- small hidden text content change
- duplicated fileUpload messages now share the same key
> ARSSTB-170: hidden text edit, file upload rename keys, 

- app/views/UploadAnotherSupportingDocumentView.scala.html
- app/views/components/Link.scala.html
- conf/messages.cy
- conf/messages.en
> ARSSTB-227 Fixing link hidden text to align with suggestions

- app/controllers/ApplicationContactDetailsController.scala
- app/controllers/BusinessContactDetailsController.scala
- app/navigation/Navigator.scala
- app/pages/AgentForOrgCheckRegisteredDetailsPage.scala
- app/userrole/AgentForOrg.scala
- app/userrole/AgentForTrader.scala
- app/userrole/Employee.scala
- app/userrole/UserRole.scala
Following conversations with payal and yemmi, the journey for cantact pages is correct, however ticket 352 is required to be done because this change breaks the check your answers submissions (basically we need the correct check your answers page detailed in 352).
> ARTSTB-348

- app/assets/stylesheets/partials/_view_application.scss
- app/views/ViewApplicationView.scala.html
- app/views/components/ForYourRecords.scala.html
- conf/messages.cy
- conf/messages.en
Jira link: [ARSSTB-360](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-360)
subtask of : [ARSSTB-231](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-231)
suggested changes made to viewApplication page regarding print preview and correct html hierarchy
Page view (with WAVE tool) -> 
Print preview ->
> ARSSTB-360: view application improvements

- app/config/FrontendAppConfig.scala
- conf/application.conf
- [ x ] Non-breaking change
I believe this is all that is needed.
> ARSSTB-335 Removed welsh translation flag

- conf/messages.en
- [ x ] Cosmetic change
Suggested fix for ui tests.
>  Potential fix

- app/controllers/ProvideTraderEoriController.scala
- app/forms/TraderEoriNumberFormProvider.scala
Allows user to input lowercase, but enforces the userAnswer to be uppecase using toUpperCase.
> ARSSTB-386 Allow lowercase for EORI input.

- app/controllers/common/FileUploadHelper.scala
[317](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-317) was branched before [320](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-320) was merged causing compilation issues in the FileUuploadHelper.
> Fix compilation errors in the new FileUploadHelper

- conf/messages.cy
- conf/messages.en
Self explanatory content change
> Consistent upload file types

- app/views/ViewUtils.scala
- conf/messages.cy
- conf/messages.en
- [ X ] Non-breaking change
Changed the suffix of each page to be Apply for an advance valuation ru....
> Update Page Titles to have "Apply for an..."

- app/forms/Validation.scala
Changed max phone number length to 24
> Changed max phone number length

- app/audit/AuditService.scala
- app/controllers/WhatIsYourRoleAsImporterController.scala
- app/models/events/AgentIndicatorEvent.scala
- app/models/events/RoleIndicatorEvent.scala
- test/audit/AuditServiceSpec.scala
- test/controllers/WhatIsYourRoleAsImporterControllerSpec.scala
Strange unrelated test failure happened last pr
> ARSSTB-319 Update audit event for role identifier question

- app/views/ContactPageView.scala.html
- conf/messages.cy
- conf/messages.en
> ARSSTB-399 Remove para 1 and update title

- app/views/UploadLetterOfAuthorityView.scala.html
- conf/messages.cy
- conf/messages.en
Last test failed for no reason?
> Added warning for password protected files.

- app/forms/BusinessContactDetailsFormProvider.scala
- app/forms/Validation.scala
Fixed duplicate validation errors appearing
> ARSSTB-383 fix

- conf/messages.cy
Jira link: [Agent creds welsh translation](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-190)
Updated a number of the welsh keys based on spreadsheet in comments of ticket
> updated welsh based on spreadsheet

- conf/messages.cy
- conf/messages.en
Jira link: [Unauthorised guidance missing](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-225)
Fixed content issues found in testing
> patched content on unauthorised page

- conf/messages.cy
Jira link: [Agent creds welsh translation](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-190)
Corrected as discussed/highlighted by Payal in comments in 190
> corrected to reflect listed errors

- app/views/ApplicationCompleteView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
Jira link: [Update 'Your applications and rulings' header](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-325)
Removed all occurrences of the text bit " and rulings". This also affects the path for the account home screen (this may have side effects for automated tests where this path is hard-coded).
> ARSSTB-325 Update 'Your applications and rulings' header

- app/views/ViewUtils.scala
- conf/messages.cy
- conf/messages.en
> ARSSTB-372 Update service banner

- app/controllers/ProvideTraderEoriController.scala
- app/forms/TraderEoriNumberFormProvider.scala
- test/controllers/ProvideTraderEoriControllerSpec.scala
Allows spaces in the EORI input but not what we send to ECC (just for the user)
> ARSSTB-429 Allow spaces in EORI input

- conf/messages.cy
- conf/messages.en
Jira link: [Changes to content displayed on check progress page from upload flow](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-445)
Removed the three dots.
> ARSSTB-445 Changes to content displayed on check progress page from upload flow

- app/controllers/UploadAnotherSupportingDocumentController.scala
- app/views/UploadAnotherSupportingDocumentView.scala.html
- conf/messages.cy
- conf/messages.en
> ARSSTB-334 Add unchanging loa to supporting docs page

- app/viewmodels/checkAnswers/summary/ApplicantSummary.scala
- conf/messages.en
> Fix bugs found by payal (whitespace and missing role)

- conf/messages.en
Jira link: [Change error message on "Describe your role as an importer"](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-435)
Updated the error message on the Describe Your Role page when nothing is selected.
> Update error message on the Describe Your Role page

- conf/messages.en
Jira link: [Error message change for Page "Are you planning to import goods into Great Britain?"](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-437)
Update the error message on the Planning To Import Goods page when nothing is selected.
> Update error message on the Planning To Import Goods page

- app/views/UploadInProgressView.scala.html
- conf/messages.cy
- conf/messages.en
> ARSSTB-445 Add p1 content to upload in progress

- app/userrole/Employee.scala
- app/viewmodels/checkAnswers/summary/ApplicantSummary.scala
- app/viewmodels/checkAnswers/summary/ApplicationSummary.scala
- app/viewmodels/checkAnswers/summary/EoriDetailsSummary.scala
- app/views/CheckYourAnswersView.scala.html
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/CheckYourAnswersForAgentsControllerSpec.scala
- test/userrole/AgentForOrgSpec.scala
- test/userrole/EmployeeSpec.scala
- test/viewmodels/checkAnswers/summary/IndividualEoriDetailsSummarySpec.scala
> ARSSTB-460 Reposition Role for Employee on CYA

- app/controllers/IsThisFileConfidentialController.scala
- app/views/IsThisFileConfidentialView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/IsThisFileConfidentialControllerSpec.scala
> ARSSTB-354 Display file on mark as confidential page

- conf/messages.cy
- conf/messages.en
> chore: fix typos

- app/viewmodels/ApplicationViewModel.scala
- app/views/IsThisFileConfidentialView.scala.html
- conf/messages.cy
- conf/messages.en
Jira link: [Content Change- Document Confidentiality](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-354)
Fix header and add question on the page which checks asks if a supporting document should be confidential.
> ARSSTB-354: Modify is file confidential page view

- app/models/requests/Application.scala
- app/models/requests/ApplicationRequest.scala
- app/models/requests/LetterOfAuthorityRequest.scala
- it/connectors/BackendConnectorSpec.scala
- test-utils/generators/ApplicationGenerator.scala
- test-utils/generators/ApplicationRequestGenerator.scala
- test/controllers/ViewApplicationControllerSpec.scala
- test/models/requests/ApplicationRequestSpec.scala
- test/services/SubmissionServiceSpec.scala
- test/viewmodels/ApplicationViewModelSpec.scala
Adds in a field for loa and extra field for contact details
> Added in a loa to request and an extra field in contact details

- app/models/requests/Application.scala
- app/viewmodels/ApplicationViewModel.scala
- app/viewmodels/application/AgentTraderDetailsSummary.scala
- app/viewmodels/application/GoodsDetailsSummary.scala
- app/viewmodels/application/RequestedMethodSummary.scala
- app/viewmodels/application/RoleDetailsSummary.scala
- test/viewmodels/ApplicationViewModelSpec.scala
- test/viewmodels/application/AgentTraderDetailsSummarySpec.scala
- test/viewmodels/application/GoodsDetailsSummarySpec.scala
- test/viewmodels/application/RequestedMethodSummarySpec.scala
Jira link: [Agent for trader: View application details page](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-458)
Modify the view application page to display answers to all of the yes/no questions, display the letter of authority, and display the role description.
Agent For Trader with all fields p1
Agent For Trader with all fields p2
Agent For Trader with minimal fields p1
Agent For Trader with minimal fields p2
> Arsstb 458

- app/controllers/CheckYourAnswersController.scala
- app/models/TraderDetailsWithConfirmation.scala
- app/userrole/AgentForOrg.scala
- app/userrole/AgentForTrader.scala
- app/userrole/Employee.scala
- app/userrole/UserRole.scala
- test/userrole/AgentForTraderSpec.scala
Jira link: [EORI for Agent for Trader coming from Auth rather than the submitted one](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-527)
Fix to check your answers controller and application summary generation to respect VerifyTraderEoriPage information
> fix for sourcing trader details on agent for trader journey

- app/viewmodels/ApplicationViewModel.scala
Jira link: [Privacy Issue Found](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-527)
No consideration of consent to display PII info on view application page. Hiding it for everyone till we can check db info
> removed trader details from application view page

- app/views/UploadSupportingDocumentsView.scala.html
- conf/messages.cy
- conf/messages.en
Jira link: [Users should be advised not to upload password protected supporting documents](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-483)
Added a new paragraph with the requested text.
> ARSSTB-483 Users should be advised not to upload password protected supporting documents

- app/views/AgentForOrgCheckRegisteredDetailsView.scala.html
- app/views/AgentForTraderCheckRegisteredDetailsView.scala.html
- app/views/AreThereRestrictionsOnTheGoodsView.scala.html
- app/views/CheckRegisteredDetailsView.scala.html
- app/views/DoYouWantToUploadDocumentsView.scala.html
- app/views/EmployeeCheckRegisteredDetailsView.scala.html
- app/views/ExplainHowPartiesAreRelatedView.scala.html
- app/views/HaveYouUsedMethodOneForSimilarGoodsInPastView.scala.html
- app/views/HaveYouUsedMethodOneInPastView.scala.html
- app/views/IsTheSaleSubjectToConditionsView.scala.html
- app/views/VerifyPublicTraderDetailView.scala.html
- conf/messages.cy
- conf/messages.en
Jira link: [Legend required on few pages of the service](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-441)
Modify h1 of many views and add legends above radio buttons. Add new English messages and overwrite Welsh with English for future translations. Also includes other minor changes like converting warning text to paragraph text.
> ARSSTB-441

- app/views/HasCommodityCodeView.scala.html
- conf/messages.en
> ARSSTB-373 Changes to do you have a commodity code page.

- app/views/UploadLetterOfAuthorityView.scala.html
- app/views/UploadSupportingDocumentsView.scala.html
- test/controllers/FileUploadHelperSpec.scala
- test/controllers/UploadInProgressControllerSpec.scala
> reverted crsf changes

- app/views/UploadSupportingDocumentsView.scala.html
Screenshot on ticket of completed.
> ARSSTB-449 Added save as draft button to Upload Supporting Docs

- app/views/AgentForOrgCheckRegisteredDetailsView.scala.html
- app/views/AgentForTraderCheckRegisteredDetailsView.scala.html
- app/views/CheckRegisteredDetailsView.scala.html
- app/views/EmployeeCheckRegisteredDetailsView.scala.html
- conf/messages.cy
- conf/messages.en
> Page title mismatch fix

- app/views/AccountHomeView.scala.html
> ARSSTB-493 Added spacing to Home Page Links

- app/controllers/UploadSupportingDocumentsController.scala
- app/models/requests/ApplicationRequest.scala
- app/viewmodels/ApplicationViewModel.scala
- it/connectors/BackendConnectorSpec.scala
- test-utils/generators/ApplicationRequestGenerator.scala
- test/controllers/ViewApplicationControllerSpec.scala
- test/models/requests/ApplicationRequestSpec.scala
- test/models/requests/ContactDetailsSpec.scala
- test/services/SubmissionServiceSpec.scala
- test/viewmodels/ApplicationViewModelSpec.scala
- test/viewmodels/application/AgentDetailsSummarySpec.scala
- test/viewmodels/application/AgentTraderDetailsSummarySpec.scala
- test/viewmodels/application/RegisteredDetailsSummarySpec.scala
Only show the trader details for an agent trader where the isPrivate is set to Some(false) otherwise don't show them
> Arsstb 528 - send an IsPrivate field to BE and use it on ViewApplication to filter private details

- conf/messages.cy
- conf/messages.en
Jira link: [User tell HMRC what their role is within the company](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-314)
fix: add hidden job title text on check answers page
> fix: add hidden job title text on check answers page

- app/viewmodels/govuk/InputFluency.scala
> fix: use a valid autofill value for the job title.

- app/views/VerifyPrivateTraderDetailView.scala.html
- conf/messages.cy
- conf/messages.en
One liner to fix the private EORI page
> ARSSTB-500 Fix private page

- app/views/AccountHomeView.scala.html
- conf/messages.cy
- conf/messages.en
Jira link: [Jira title](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-491)
> ARSSTB-491 Added actions as column header to AccountHome

- app/views/RemoveSupportingDocumentView.scala.html
- conf/messages.cy
- conf/messages.en
Jira link: [Jira title](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-517)
Move the filename out of the h1 to avoid potential overflow issues.
> ARSSTB-517: Fix h1 overflow issue

- app/views/IsThisFileConfidentialView.scala.html
- app/views/UploadAnotherSupportingDocumentView.scala.html
- [x ] Cosmetic change
[Jira link](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-566)
Changed the table on the "mark file confidential" page to an inset, and the tables on the "uploaded document(s)" page to summary lists
> ARSSTB-566: Replace tables

- app/navigation/Navigator.scala
- app/pages/AgentForTraderContactDetailsPage.scala
- app/userrole/AgentForTrader.scala
- app/views/ChoosingMethodView.scala.html
- app/views/ValuationMethodView.scala.html
- conf/messages.cy
- conf/messages.en
- test/navigation/NavigatorSpec.scala
> ARSSTB-369 Fixes

- app/controllers/AboutSimilarGoodsController.scala
- app/controllers/AwareOfRulingController.scala
- app/forms/AboutSimilarGoodsFormProvider.scala
- app/forms/AwareOfRulingFormProvider.scala
- app/navigation/Navigator.scala
- app/pages/AboutSimilarGoodsPage.scala
- app/pages/AwareOfRulingPage.scala
- app/views/AboutSimilarGoodsView.scala.html
- app/views/AwareOfRulingView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/AboutSimilarGoodsControllerSpec.scala
- test/controllers/AwareOfRulingControllerSpec.scala
- test/forms/AboutSimilarGoodsFormProviderSpec.scala
- test/forms/AwareOfRulingFormProviderSpec.scala
- test/navigation/NavigatorSpec.scala
Jira link: [Trader Provide details on similar or same Ruling](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-310)
_Provide a short description of the change. For example: what parts of the code changed, is there any new behaviour...etc._
> ARSSTB-310 added awareofrulings and aboutsimilargoods pages

- app/navigation/Navigator.scala
- test/navigation/NavigatorSpec.scala
Jira link: [Fixed page order](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-310)
> fixed page flow error

- project/AppDependencies.scala
> Updated object-store-client-play-28

- project/AppDependencies.scala
- [X ] Non-breaking change
Updated library version for test and compile
> Updated hmrc-mongo-play-28 and hmrc-mongo-test-play-28

- project/AppDependencies.scala
- [ X] Non-breaking change
Only had to change the version number here
> Updated version for internal-auth-client-play-28

- app/views/AccountHomeView.scala.html
- [ x] Non-breaking change
Jira link: [Jira title](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-520)
also fixes  https://jira.tools.tax.service.gov.uk/browse/ARSSTB-492
Updated Your Applications table links to include contextual copy.
View application
Delete application
Continue application
Screen-reader dialog showing contextual links for the 3 types:
> ARSSTB-520 Updated applications contextual copy

- app/views/UploadLetterOfAuthorityView.scala.html
- app/views/UploadSupportingDocumentsView.scala.html
- conf/messages.cy
- conf/messages.en
- [x ] Cosmetic change
Jira link: [Jira title](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-565)
Updated both upload pages (Supporting docs & Letter of Authority):
- added Error prefix to page title, with translation
- added Welsh translation to error message above input
- re-ordered label/error message
- tied error message to input via aria
- changed from hard-coded html to importing GovUK component for file upload (incl error message and label)
> ARSSTB-565 Update error formatting on upload pages

- app/views/AgentCompanyDetailsView.scala.html
Jira link: [Jira title](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-619)
> ARSSTB-619 Added and ammended autocomplete on details page.

- app/viewmodels/checkAnswers/ApplicationContactDetailsSummary.scala
- app/viewmodels/checkAnswers/BusinessContactDetailsSummary.scala
- test/viewmodels/checkAnswers/summary/AgentSummarySpec.scala
- test/viewmodels/checkAnswers/summary/IndividualApplicantSummarySpec.scala
Jira link: [Jira title](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-502)
> ARSSTB-502 Allow apostrophes in CYA

- app/views/AgentForOrgRequiredInformationView.scala.html
- app/views/IndividualInformationRequiredView.scala.html
- app/views/components/SaveButtonsWithTarget.scala.html
Jira link: [Zap Test Failure - Anti-CSRF Tokens](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-585)
Removed the form from the Required Information views
> removed form from RequiredInformation views

- conf/application.conf
Removed various config keys that are already provided by Bootstrap
> Removed various config keys that are already provided by Bootstrap

- conf/messages.cy
Jira link: [Welsh Applications Home missing translations [WCAG]](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-523)
Before:
After:
> ARSSTB-523

- app/views/AboutSimilarGoodsView.scala.html
- app/views/TellUsAboutYourRulingView.scala.html
> ARSSTB-427 Max length Update

- app/views/AgentForTraderRequiredInformationView.scala.html
> fixed form on agentfortrader version of page

- build.sbt
- project/plugins.sbt
- scalastyle-config.xml
Jira link: [ARSSTB-606](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-606)
Added and tested scalastyle plugins for handover to the live team.
> ARSSTB-606: Implement scalastyle plugin

- app/views/components/YesNoRadios.scala.html
Jira link: [Jira title](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-509)
> ARSSTB-509

- app/views/ExplainHowYouWillUseMethodSixView.scala.html
- app/views/ExplainReasonComputedValueView.scala.html
- app/views/ExplainWhyYouChoseMethodFourView.scala.html
- app/views/HaveYouUsedMethodOneForSimilarGoodsInPastView.scala.html
- app/views/HaveYouUsedMethodOneInPastView.scala.html
- conf/messages.en
> ARSSTB-575 Fixes

- app/controllers/common/FileUploadHelper.scala
- test/controllers/FileUploadHelperSpec.scala
Remove the hardcoding of the appname. It's available from the frontend config so get it from that
> Get config name from frontend config

- app/models/requests/ApplicationRequest.scala
> Removed TODO - won't fix

- app/views/AwareOfRulingView.scala.html
> 575 Value hint fix

- conf/messages.cy
Jira link: [Accessible names of check answers links](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-520)
Updated Welsh translations.
> ARSSTB-520 Added translations to CYA page

- app/models/requests/ApplicationRequest.scala
- app/models/requests/ContactDetails.scala
- app/navigation/Navigator.scala
- app/userrole/AgentForOrg.scala
- app/userrole/AgentForTrader.scala
- app/userrole/Employee.scala
- app/userrole/UserRole.scala
- test/models/requests/ApplicationRequestSpec.scala
- test/models/requests/ContactDetailsSpec.scala
- test/navigation/NavigatorSpec.scala
- test/userrole/AgentForOrgSpec.scala
- test/userrole/AgentForTraderSpec.scala
- test/userrole/EmployeeSpec.scala
Previously the logic for the contact details page came from the authtype. Now comes from the userrole
Breaking because, for example, if a user logged in as Org Assist and then did an employee run previously would have got a BusinessContactDetails now gets an ApplicationContactDetails
> Moved logic for contact details to userrole as it was using the AuthTYpe

- conf/messages.cy
- conf/messages.en
Jira link: [Update check your answers page to reflect additional questions](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-473)
Added missing message key and added improvised hidden keys
> ARSSTB-473 added hidden and other missing message keys

- conf/messages.cy
- conf/messages.en
> ARSSTB-674, ARSSTB-654 Small Welsh Changes

- app/controllers/BusinessContactDetailsController.scala
- app/navigation/CheckModeNavigator.scala
- app/navigation/Navigator.scala
- test/navigation/CheckModeNavigatorSpec.scala
- test/navigation/FakeNavigator.scala
- test/navigation/NavigatorSpec.scala
Removed AuthType and flag from Navigator
> Removed flag from Navigator and removed AuthType from Navigator

- conf/messages.cy
- conf/messages.en
> ARSSTB-677 CYA Welsh

- conf/messages.cy
- conf/messages.en
> ARSSTB-675 Choosing method title + welsh

- app/config/FrontendAppConfig.scala
- app/controllers/CheckRegisteredDetailsController.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/EORIBeUpToDateController.scala
- app/controllers/RequiredInformationController.scala
- app/controllers/UploadSupportingDocumentsController.scala
- app/models/WhatIsYourRoleAsImporter.scala
- app/viewmodels/checkAnswers/summary/ApplicationSummary.scala
- app/views/WhatIsYourRoleAsImporterView.scala.html
- test/controllers/CheckRegisteredDetailsControllerSpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/EORIBeUpToDateControllerSpec.scala
- test/controllers/RequiredInformationControllerSpec.scala
- test/controllers/UploadInProgressControllerSpec.scala
- test/controllers/UploadSupportingDocumentsControllerSpec.scala
- test/navigation/CheckModeNavigatorSpec.scala
> Remmoved usages of agent creds flag

- conf/application.conf
- test/resources/application.conf
Jira link: [play.filters.headers.contentSecurityPolicy should be removed from config as it is deprecated](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-539)
Removed old filter and added default filter (as we are post 7.15 we're good with doing that) and removed filter from tests because otherwise *every test of the views fail*
> ARSSTB-539

- app/forms/AgentCompanyDetailsFormProvider.scala
- app/forms/TraderEoriNumberFormProvider.scala
- app/forms/mappings/Constraints.scala
- app/views/AgentCompanyDetailsView.scala.html
- app/views/ProvideTraderEoriView.scala.html
- conf/messages.cy
- conf/messages.en
- test-utils/generators/Generators.scala
- test/controllers/AgentCompanyDetailsControllerSpec.scala
- test/forms/AgentCompanyDetailsFormProviderSpec.scala
- test/forms/behaviours/FieldBehaviours.scala
- test/forms/mappings/ConstraintsSpec.scala
Jira link: [EORI number pattern not followed [WCAG AA]](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-617)
Modify the Provide trader EORI view to replace the paragraph with hint text and change the heading to a question. Ensure there is validation for the EORI field on the AgentCompanyDetails page.
Not all of the Welsh translation is in place: this will be in a later PR
> Arsstb 617

- conf/messages.cy
Jira link: [EORI number pattern not followed [WCAG AA]](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-617)
Fix Welsh message.
> fix: update Welsh message

- conf/messages.cy
- conf/messages.en
> ARSSTB-677 Fixed wrong hidden text ammendments

- conf/messages.cy
- conf/messages.en
> Welsh changes and additions

- app/views/AboutSimilarGoodsView.scala.html
- app/views/AgentForOrgCheckRegisteredDetailsView.scala.html
- app/views/ConfidentialInformationView.scala.html
- app/views/DescribeTheIdenticalGoodsView.scala.html
- app/views/DescribeTheSimilarGoodsView.scala.html
- app/views/ExplainHowPartiesAreRelatedView.scala.html
- app/views/ExplainHowYouWillUseMethodSixView.scala.html
- app/views/ExplainReasonComputedValueView.scala.html
- app/views/ExplainWhyYouChoseMethodFourView.scala.html
- app/views/ExplainWhyYouHaveNotSelectedMethodOneToFiveView.scala.html
- app/views/ExplainWhyYouHaveNotSelectedMethodOneToThreeView.scala.html
- app/views/HaveYouUsedMethodOneForSimilarGoodsInPastView.scala.html
- app/views/HaveYouUsedMethodOneInPastView.scala.html
- app/views/WhyComputedValueView.scala.html
- app/views/WhyIdenticalGoodsView.scala.html
- app/views/WhyTransactionValueOfSimilarGoodsView.scala.html
- app/views/components/ApplicationSummaryList.scala.html
- app/views/components/ApplyButtonWithDraft.scala.html
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
- test/models/requests/ApplicationRequestSpec.scala
AVR - Implement button double click prevention
> DDCE-4960: Adding code to prevent double click for the submit button in the ApplyButtonWithDraft Component

- app/viewmodels/govuk/InputFluency.scala
- project/AppDependencies.scala
DDCE-4880 - Your contact details telephone field should use telephone type [P2]
> DDCE-4880 - Your contact details telephone field should use telephone type [P2]

- app/views/AccountHomeView.scala.html
- project/AppDependencies.scala
DDCE-4860 - AVR - Caption missing on Your applications table [P2]
> DDCE-4860 - AVR - Caption missing on Your applications table [P2]

- app/views/AgentForOrgRequiredInformationView.scala.html
- app/views/AgentForTraderRequiredInformationView.scala.html
- app/views/ContactPageView.scala.html
- app/views/IndividualInformationRequiredView.scala.html
- conf/messages.cy
- conf/messages.en
Content updates to remove caption from screen [P2] (Remove the 'About the applicant' caption)
> Content updates to remove caption from screen [P2] (Remove the 'About the applicant' caption)

- app/views/templates/Layout.scala.html
- project/AppDependencies.scala
Ddce 6509 - AVR - Fix javascript file 404 (not found)
> Ddce 6509 - AVR - Fix javascript file 404 (not found)
